name: Publish on Bever Marketplace CI

on:
  push:
    branches: release

jobs:
  main:
    uses: BeverCRM/Workflow-Build-Release-Upload-Update/.github/workflows/build-release-upload-update-rw.yml@master
    secrets: inherit
    with:
      control-title: Fetch to Subgrid
      control-description: This control converts a FetchXml string into a subgrid.
      control-tags: Field, Grid, FetchXml
      # control-youtube-video-url: '' # default
